// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBNromMKJRXrqCEOsrutCZ7uhKiQzcDhU',
    appId: '1:894623823230:web:7f917d893f0081942a2f2f',
    messagingSenderId: '894623823230',
    projectId: 'excel-2f298',
    authDomain: 'excel-2f298.firebaseapp.com',
    storageBucket: 'excel-2f298.firebasestorage.app',
    measurementId: 'G-EZX087VKND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADELDOphmLCzSTHgF5PlfYGwD00mvzpXI',
    appId: '1:894623823230:android:324c63d850d1f40a2a2f2f',
    messagingSenderId: '894623823230',
    projectId: 'excel-2f298',
    storageBucket: 'excel-2f298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZA1mt5jYarwnDmprbCAqUPWfL3LU304',
    appId: '1:894623823230:ios:44dea265615af5be2a2f2f',
    messagingSenderId: '894623823230',
    projectId: 'excel-2f298',
    storageBucket: 'excel-2f298.firebasestorage.app',
    iosBundleId: 'com.example.excel',
  );
}
